---
- hosts: all
  connection: ssh
  gather_facts: no
#  become: true
#  become_method: sudo
  remote_user: ubuntu
  tasks:
  #  - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
  #    file:
  #     path: /etc/foo.conf
  #     state: touch
  #     mode: u=rw,g=r,o=r

    - name: Upgrade all packages to the latest version
      apt:
       name: "*"
       state: latest
       

       
    - name: install the latest version of git
      apt:
       name: git
       state: latest
       
    - name: install the latest version of zip
      apt:
       name: zip
       state: latest
