---
- hosts: all
  connection: ssh
  remote_user: ec2-user
  gather_facts: no
  tasks:
    - name: upgrade all packages
      yum:
       name: '*'
       state: latest

    - name: Install a list of packages
      yum:
       name:
        - nginx
        - postgresql
        - postgresql-server
       state: present


