---
- hosts: all
  connection: ssh
  remote_user: ec2-user
  gather_facts: no
  tasks:
    - name: Upgrade all packages to the latest version
      yum:
       name: httpd
       state: latest

    - name: 4. install Apache
      yum:
        name: git
        state: latest
        install_recommends: yes


