---
- hosts: all
  connection: ssh
  remote_user: ec2-user
  gather_facts: no
  tasks:
      
    - name: Change file ownership, group and permissions
      file:
       path: /etc/foo.conf
       owner: foo
       group: foo
       mode: '0644'


