---
- hosts: dev
  connection: ssh
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: Install apache httpd  (state=present is optional)
      apt:
       name: apache2
       state: present

    - name: 6. insstall php
      apt:
        name: php7.0
        state: latest
        install_recommends: yes
