
---
- hosts: dev
  connection: ssh
  remote_user: ubuntu
  gather_facts: no
  tasks:
    - name: Install apache httpd  (state=present is optional)
      apt:
       name: apache2
       state: present

    - name: Upgrade all packages to the latest version
      apt:
       name: "*"
       state: latest

    - name: 4. install Apache
      apt:
        name: apache2
        state: latest
        install_recommends: yes

    - name: Add repository for PHP versions (Ubuntu).
      apt_repository: 
        repo: 'ppa:ondrej/php'
        
    - name: Upgrade all packages to the latest version
      apt:
       name: "*"
       state: latest




