  
---
- hosts: all
  connection: ssh
  gather_facts: no
#  become: true
#  become_method: sudo
#  remote_user: ec2-user
  tasks:
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      file:
       path: /etc/foo.conf
       state: touch
       mode: u=rw,g=r,o=r
      become_user: root

    - name: Upgrade all packages to the latest version
      yum:
       name: "*"
       state: latest
      become_user: root 
       
    - name: install the latest version of Apache
      yum:
       name: httpd
       state: latest
      become_user: root       
    - name: install the latest version of git
      yum:
       name: git
       state: latest
      become: true
      become_user: root 
       
    - name: install the latest version of zip
      yum:
       name: zip
       state: latest
      become: true
      become_user: root 

