  
---
- hosts: all
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install apache httpd  (state=present is optional)
      yum:
       name: apache
       state: present

    - name: Upgrade all packages to the latest version
      yum:
       name: "*"
       state: latest


